spring:
  application:
    name: catalog

server:
  port: 8080
  servlet:
    context-path: /catalog

api:
  product: ${PRODUCT_URL}/products

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
