spring:
  application:
    name: checkout
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST}

server:
  port: 8082
  servlet:
    context-path: /checkout

api:
  product: ${PRODUCT_URL}/products


queue:
  checkout:
    name: checkout_queue

exchange:
  checkout:
    name: checkout_ex
