spring:
  application:
    name: checkout
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /

server:
  port: 8082
  servlet:
    context-path: /checkout

api:
  product: http://localhost:8081/products


queue:
  checkout:
    name: checkout_queue

exchange:
  checkout:
    name: checkout_ex
