spring:
  application:
    name: order
  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: 8083
  servlet:
    context-path: /order


queue:
  checkout:
    name: checkout_queue
  order:
    name: order_queue
  payment:
    name: payment_queue

exchange:
  order:
    name: order_ex

logging:
  level:
    root: INFO
    com:
      shop:
        order: DEBUG
  file:
    name: order.log

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
