spring:
  application:
    name: order
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8086
  servlet:
    context-path: /order


queue:
  checkout:
    name: checkout_queue
  order:
    name: order_queue

exchange:
  order:
    name: order_ex
